image: Ubuntu


stack: jdk 11


branches:
  only:
    - master


build: off

install:

  - java -jar ./artifacts/app-card-delivery.jar &


build_script:
  - gradlew test -Dselenide.headless=true
  - chmod +x gradlew
  - ./gradlew test --info